# Generated by Django 3.2.6 on 2021-08-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='quotes',
        ),
        migrations.AlterField(
            model_name='quotes',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.characters'),
        ),
    ]
