# Generated by Django 3.2.6 on 2021-08-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210802_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
